[package]
name = "cairo1_v2"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
# foo = { path = "vendor/foo" }
starknet = ">=2.0.2"

[cairo]
sierra-replace-ids = true

[[target.starknet-contract]]
sierra = true